import 'dart:io';
import 'package:excel/excel.dart';
import 'package:file_picker/file_picker.dart';
import '../models/question_model.dart';
import 'package:flutter/foundation.dart';

class QuestionImportService {
  /* 
  Expected Excel Format:
  Row 1: Header (Ignored)
  Column A: Question Text
  Column B: Question Type (mcq, true_false, completion)
  Column C: Points (e.g., 2)
  Column D: Correct Answer (For MCQ: option index 0-3, For T/F: true/false, For Completion: the text)
  Column E: Option 1 (Required for MCQ)
  Column F: Option 2 (Required for MCQ)
  Column G: Option 3 (Optional for MCQ)
  Column H: Option 4 (Optional for MCQ)
  */

  static Future<List<Question>> importFromExcel(String lessonId) async {
    FilePickerResult? result = await FilePicker.platform.pickFiles(
      type: FileType.custom,
      allowedExtensions: ['xlsx'],
    );

    if (result == null || result.files.single.path == null) return [];

    var bytes = File(result.files.single.path!).readAsBytesSync();
    var excel = Excel.decodeBytes(bytes);
    List<Question> questions = [];

    for (var table in excel.tables.keys) {
      var rows = excel.tables[table]?.rows;
      if (rows == null || rows.isEmpty) continue;

      // Skip header row
      for (int i = 1; i < rows.length; i++) {
        var row = rows[i];
        if (row.isEmpty || row[0] == null) continue;

        try {
          String text = row[0]?.value?.toString() ?? '';
          if (text.isEmpty) continue;

          String typeStr =
              row[1]?.value?.toString().toLowerCase().trim() ?? 'mcq';
          QuestionType type = QuestionType.fromString(typeStr);

          int points = int.tryParse(row[2]?.value?.toString() ?? '1') ?? 1;
          String correctAnswer = row[3]?.value?.toString() ?? '';

          Map<String, dynamic> config = {};

          if (type == QuestionType.mcq) {
            List<String> options = [];
            for (int j = 4; j <= 7; j++) {
              if (row.length > j && row[j] != null) {
                String opt = row[j]?.value?.toString() ?? '';
                if (opt.isNotEmpty) options.add(opt);
              }
            }
            config = {
              'options': options,
              'correct_answer': int.tryParse(correctAnswer) ?? 0,
            };
          } else if (type == QuestionType.true_false) {
            config = {'correct_answer': correctAnswer.toLowerCase() == 'true'};
          } else {
            // completion
            config = {'correct_answer': correctAnswer};
          }

          questions.add(
            Question(
              id: '', // Will be generated by DB
              lessonId: lessonId,
              questionText: text,
              questionType: type,
              config: config,
              points: points,
              createdAt: DateTime.now(),
            ),
          );
        } catch (e) {
          debugPrint('Error parsing row $i: $e');
        }
      }
    }
    return questions;
  }
}
